spring.application.name=mcp
spring.datasource.url=jdbc:h2:file:./database;AUTO_SERVER=TRUE;
spring.jpa.hibernate.ddl-auto=update
spring.mvc.apiversion.use.path-segment=0
spring.mvc.apiversion.default=v1
logging.level.com.scyed.clu = trace

management.endpoints.web.exposure.include=*

scyed.eggs.directory=./eggs
scyed.gameserver.installTemp=./pt/installTemp
scyed.gameserver.gameserver-storage=./pt/gmStorage
scyed.gameserver.user-uid=1000
scyed.gameserver.user-gid=1000
