spring.datasource.url=jdbc:postgresql://ep-divine-salad-ast9a74n.c-4.eu-central-1.aws.neon.tech/neondb?sslmode=require&user=neondb_owner&password=npg_7IPcUOGZVKY2
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.auto-commit=true
