spring.application.name=clu
spring.mvc.apiversion.use.path-segment=0
spring.mvc.apiversion.default=v1
logging.level.com.scyed.clu = trace

spring.datasource.url=jdbc:sqlite:./database.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=*

spring.web.error.include-stacktrace=never
spring.web.error.include-binding-errors=never

scyed.eggs.directory=./eggs
scyed.gameserver.installTemp=./pt/installTemp
scyed.gameserver.gameserver-storage=./pt/gmStorage
scyed.gameserver.user-uid=1001
scyed.gameserver.user-gid=1001

scyed.environment.gm-storage-dataset=blink
scyed.environment.gm-storage-path=/blink
